### generated by chatGPT based on the existing code for ROC curves in 
# iCOBRA.R ### 

library("dplyr")
library("tidyr")
library("iCOBRA")
library("ggplot2")
library("patchwork")

set.seed(1234)

# ------------------------------------------------------------------
# Read and reshape results
# ------------------------------------------------------------------

results <- readRDS(snakemake@input[["rds"]])

nSim <- 200

results <- results %>%
  group_by(lambda, simulation) %>%
  mutate(repetition = row_number()) %>%
  ungroup() %>%
  mutate(
    ID = paste(lambda, simulation, repetition, sep = "_")
  )

results <- results %>%
  pivot_longer(
    cols = c(
      spicyRLM,
      spicyRMM,
      spatialFDAL,
      spatialFDAG,
      intensityMM,
      smoppix,
      mxfdaFM,
      mxfdaMM,
      spaceANOVAUni,
      spaceANOVAMulti
    ),
    names_to = "method",
    values_to = "p.value"
  ) %>%
  mutate(
    method = case_when(
      method == "spicyRLM"         ~ "spicyR.LM",
      method == "spicyRMM"         ~ "spicyR.MM",
      method == "spaceANOVAUni"    ~ "SpaceANOVA.Uni",
      method == "spaceANOVAMulti"  ~ "SpaceANOVA.Multi",
      method == "spatialFDAL"      ~ "spatialFDA.L",
      method == "spatialFDAG"      ~ "spatialFDA.G",
      method == "smoppix"          ~ "smoppix",
      method == "intensityMM"      ~ "intensity.MM",
      method == "mxfdaFM"          ~ "mxfda",
      method == "mxfdaMM"          ~ "mxfda.MM"
    ),
    p.value = as.numeric(p.value)
  ) %>%
  filter(lambda %in% c(10, 30, 50, 70, 90, 100))


method_order <- c(
  "intensity.MM",
  "smoppix",
  "spicyR.LM",
  "spicyR.MM",
  "SpaceANOVA.Multi",
  "SpaceANOVA.Uni",
  "spatialFDA.G",
  "spatialFDA.L",
  "mxfda",
  "mxfda.MM"
)

results$method <- factor(results$method, levels = method_order)


colors <- c(
  intensity.MM      = "#A6CEE3",
  smoppix           = "#1F78B4",
  SpaceANOVA.Uni    = "#33A02C",
  SpaceANOVA.Multi  = "#B2DF8A",
  spatialFDA.L      = "#E31A1C",
  spatialFDA.G      = "#FB9A99",
  spicyR.LM         = "#FDBF6F",
  spicyR.MM         = "#FF7F00",
  mxfda             = "#CAB2D6",
  mxfda.MM          = "#6A3D9A"
)


# ------------------------------------------------------------------
# Prepare iCOBRA object
# ------------------------------------------------------------------

iCobraPlot <- function(results, overall = FALSE) {

  df <- results %>%
    group_by(lambda, simulation, method) %>%
    mutate(repetition = row_number()) %>%
    ungroup() %>%
    mutate(
      truth = as.integer(simulation == "Signal"),
      ID = paste(lambda, simulation, repetition, sep = "_")
    )

  df_wide <- df %>%
    select(
      ID,
      lambda,
      simulation,
      repetition,
      truth,
      method,
      p.value
    ) %>%
    pivot_wider(
      names_from = method,
      values_from = p.value
    ) %>%
    as.data.frame()

  rownames(df_wide) <- df_wide$ID

  pval <- df_wide %>%
    select(all_of(method_order))

  truth <- df_wide %>%
    select(ID, truth, lambda)

  cobraData <- COBRAData(
    pval = pval,
    truth = truth
  )

  cobraData <- calculate_adjp(cobraData)

  if (overall) {

    cobraPerf <- calculate_performance(
      cobraData,
      binary_truth = "truth",
      aspects = c("fdrtpr", "fdrtprcurve", "roc")
    )

  } else {

    cobraPerf <- calculate_performance(
      cobraData,
      binary_truth = "truth",
      splv = "lambda",
      maxsplit = Inf,
      aspects = c("fdrtpr", "fdrtprcurve", "roc")
    )
  }

  cobraPlot <- prepare_data_for_plot(
    cobraPerf,
    colorscheme = colors,
    facetted = TRUE,
    incloverall = overall
  )

  cobraPlot <- reorder_levels(
    cobraPlot,
    method_order
  )

  return(cobraPlot)
}

plotFDPROCCurves <- function(dataSplit) {

  # --------------------------------------------------------------
  # ROC
  # --------------------------------------------------------------

  pROC <- plot_roc(
    dataSplit,
    linewidth = 1
  ) +
    coord_cartesian(xlim = c(0, 0.25)) +
    theme_classic() +
    theme(
      axis.text.x = element_text(
        angle = 90,
        vjust = 0.5,
        hjust = 1,
        size = 14
      ),
      axis.text.y = element_text(size = 14),
      axis.title.x = element_text(size = 14),
      axis.title.y = element_text(size = 14),
      plot.title = element_text(size = 14, face = "bold"),
      legend.text = element_text(size = 14),
      strip.text.x = element_text(size = 14),
      legend.position = "bottom",
      legend.key = element_blank(),
      legend.background = element_blank(),
      legend.box.background = element_blank()
    ) +
    guides(
      colour = guide_legend(
        override.aes = list(
          shape = 16,
          size = 5,
          stroke = 0,
          alpha = 1
        )
      )
    )


  # 3 columns for lambda = 10,30,50,70,90,100
  pROC$facet$params$ncol <- 3
  pROC$facet$params$nrow <- NULL


  # --------------------------------------------------------------
  # Achieved FDR vs TPR
  # --------------------------------------------------------------

  fdr_obs <- fdrtpr(dataSplit) |> select(method, thr, FDR, TPR, splitval)
	fdr_obs$FDRMCSE <- sqrt(fdr_obs$FDR * (1-fdr_obs$FDR)/nSim)

	fdr_obs$fdrhi <- fdr_obs$FDR + 1.96 * fdr_obs$FDRMCSE 
	fdr_obs$fdrlo <- fdr_obs$FDR - 1.96 * fdr_obs$FDRMCSE 

  pFDP <- plot_fdrtprcurve(
    dataSplit,
    pointsize = 4,
    linewidth = 1,
    plottype = "points"
  ) +
    xlab("achieved FDR") +
    coord_cartesian(xlim = c(0, 0.25)) +
    theme_classic() +
    geom_errorbar(
			data        = fdr_obs,
			mapping     = aes(y = TPR,
												xmin = fdrlo,
												xmax = fdrhi,
												colour = method),
			width      = 0.03,
			linewidth   = 0.75,
			inherit.aes = FALSE
			) +
    theme(
      axis.text.x = element_text(
        angle = 90,
        vjust = 0.5,
        hjust = 1,
        size = 14
      ),
      axis.text.y = element_text(size = 14),
      axis.title.x = element_text(size = 14),
      axis.title.y = element_text(size = 14),
      plot.title = element_text(size = 14, face = "bold"),
      legend.text = element_text(size = 14),
      strip.text.x = element_text(size = 14),
      legend.position = "bottom",
      legend.key = element_blank(),
      legend.background = element_blank(),
      legend.box.background = element_blank()
    ) +
    guides(
      colour = guide_legend(
        override.aes = list(
          shape = 16,
          size = 5,
          stroke = 0,
          alpha = 1
        )
      )
    )

  pFDP$facet$params$ncol <- 3
  pFDP$facet$params$nrow <- NULL


  return(
    list(
      pFDP = pFDP,
      pROC = pROC
    )
  )
}

# ------------------------------------------------------------------
# Lambda-specific performance
# ------------------------------------------------------------------

dataSplit <- iCobraPlot(
  results = results,
  overall = FALSE
)

plotsSplit <- plotFDPROCCurves(dataSplit)

pFDPSplit <- plotsSplit$pFDP
pROCSplit <- plotsSplit$pROC

# ------------------------------------------------------------------
# Combine overall + lambda-specific
# ------------------------------------------------------------------

pFDP <- (
  pFDPSplit
) +
  plot_layout(guides = "collect") +
  plot_annotation(tag_levels = "A") &
  theme(
    plot.tag = element_text(size = 20),
    legend.position = "bottom"
  )


pROC <- (
  pROCSplit
) +
  plot_layout(guides = "collect") +
  plot_annotation(tag_levels = "A") &
  theme(
    plot.tag = element_text(size = 20),
    legend.position = "bottom"
  )


# ------------------------------------------------------------------
# Save
# ------------------------------------------------------------------

ggsave(
  snakemake@output[["fdp"]],
  plot = pFDP,
  width = 9,
  height = 9
)

ggsave(
  snakemake@output[["roc"]],
  plot = pROC,
  width = 9,
  height = 9
)